# Classification using Single Perceptron

In [1]:
#Detecting whether our patient have MI Disease or Angina Disease depending upon SYSTLOC BLOOD PRESSURE and WHITE BLOOD COUNT

In [2]:
#Importing some common python libraries
import pandas as pd
import numpy as np

### Loading our Training Dataset 

In [3]:
# loading data file into the program. give the location of your csv file
train = pd.read_csv("MI vs Angina.csv")
train.head(10)

SBP    WBC Diagnosis
0  10.01  16.58        MI
1  13.81  19.77        MI
2  12.42  11.20        MI
3  11.39  15.87        MI
4   8.14  18.46        MI
5  12.06  10.61        MI
6  10.93  11.46        MI
7  10.58  15.16        MI
8  10.17  19.65        MI
9   9.46  15.97        MI

In [4]:
#Converting data into numeric
# MI = 0
# Angina = 1
train.replace('MI',0,inplace=True)
train.replace('Angina',1,inplace=True)

In [5]:
train.head()

SBP    WBC  Diagnosis
0  10.01  16.58          0
1  13.81  19.77          0
2  12.42  11.20          0
3  11.39  15.87          0
4   8.14  18.46          0

In [6]:
# Converting our data to numpy matrix
train = np.asmatrix(train)
train

matrix([[10.01, 16.58,  0.  ],
        [13.81, 19.77,  0.  ],
        [12.42, 11.2 ,  0.  ],
        [11.39, 15.87,  0.  ],
        [ 8.14, 18.46,  0.  ],
        [12.06, 10.61,  0.  ],
        [10.93, 11.46,  0.  ],
        [10.58, 15.16,  0.  ],
        [10.17, 19.65,  0.  ],
        [ 9.46, 15.97,  0.  ],
        [21.98,  7.39,  1.  ],
        [16.8 ,  7.35,  1.  ],
        [14.85,  6.15,  1.  ],
        [16.39,  5.41,  1.  ],
        [20.05,  7.11,  1.  ],
        [14.8 ,  7.65,  1.  ],
        [19.98,  7.7 ,  1.  ],
        [16.81,  3.85,  1.  ],
        [18.77,  5.86,  1.  ],
        [21.7 ,  9.19,  1.  ]])

### Defining our MODEL 

In [7]:
# Function for estimating Perceptron weights
def perceptron(data, epoch):
    features = data[:, :-1]
    labels = data[:, -1]
    
    # set weights to zero
    w = np.zeros(shape=(1, features.shape[1]+1))
    
    misclassified_ = []
  
    for epoch in range(epoch):
        misclassified = 0
        for x, label in zip(features, labels):
            x = np.insert(x,0,1)
            y = np.dot(w, x.transpose())
            target = 1.0 if (y > 0) else 0.0
            
            delta = (label.item(0,0) - target)
            
            if(delta): # misclassified
                misclassified += 1
                w += (delta * x)
        
        misclassified_.append(misclassified)
    return (w)

In [8]:
# Function for prediction using weghts
def test_(data, w):
    features = data[:, :-1]
    labels = data[:, -1]
    truth = []
    for x, label in zip(features, labels):
        x = np.insert(x,0,1)
        y = np.dot(w, x.transpose())
        target = 1.0 if (y > 0) else 0.0
        truth.append(target)
    return truth

### Training / Determining Weights

In [9]:
# Number of Epochs
epoch = 10
weights = perceptron(train, epoch)
print("Weights:")
print(weights[0])

Weights:
[ -1.    26.8  -50.78]


### TEST Dataset 

In [10]:
test = pd.DataFrame(columns=['SBP','WBC','Diagnosis'])
test['Diagnosis'] = ["MI","MI","MI","MI","MI","Angina","Angina","Angina","Angina","Angina"]
test['SBP'] = [10.13,  8.64, 12.75, 10.17, 12.83, 21.03, 20.22, 15.63, 19.99, 15.41]
test['WBC'] = [12.6 , 14.66, 21.64, 12.35, 11.95,  4.97,  6.82,  4.98,  7.15, 5.44]
test.head()

SBP    WBC Diagnosis
0  10.13  12.60        MI
1   8.64  14.66        MI
2  12.75  21.64        MI
3  10.17  12.35        MI
4  12.83  11.95        MI

In [11]:
#Converting data into numeric
# MI = 0
# Angina = 1
test.replace('MI',0,inplace=True)
test.replace('Angina',1,inplace=True)

In [12]:
# Converting our data to numpy array
test = test.to_numpy()
test

array([[10.13, 12.6 ,  0.  ],
       [ 8.64, 14.66,  0.  ],
       [12.75, 21.64,  0.  ],
       [10.17, 12.35,  0.  ],
       [12.83, 11.95,  0.  ],
       [21.03,  4.97,  1.  ],
       [20.22,  6.82,  1.  ],
       [15.63,  4.98,  1.  ],
       [19.99,  7.15,  1.  ],
       [15.41,  5.44,  1.  ]])

### Prediction 

In [13]:
# Using Weights from training
pred = test_(test, weights[0])

In [14]:
pred

[0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0]

### Working for Accuracy 

In [15]:
# checking if the result of our model and true labels are matching
accuracy_list = []
# making list of True values from test data
TrueLabel = test[:,-1]

for i in range(0,10):
    if pred[i] == TrueLabel[i]:
        accuracy_list.append(1)
    else:
        accuracy_list.append(0)

In [16]:
# 1 = True
# 0 = False
accuracy_list

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [17]:
Total_values = 10
Sum = sum(accuracy_list)

In [18]:
#Formula for Accuracy Percent
Accuracy = (Sum/Total_values)*100

### Accuracy of Single Perceptron

In [19]:
print('Accuracy = %d'% Accuracy + "%")

Accuracy = 100%
